on: [push, pull_request]
name: test and build
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16.x
      - run: echo "GOBIN=$HOME/.local/bin" >> $GITHUB_ENV
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: make ci-tidy
      - run: make install
      - run: cd test && make -f ../Makefile generate
      - run: cd test && make -f ../Makefile vet
